---
name: Emacs-Run-ExtractDocs
version: 0.03
author:
  - 'Joseph Brenner <doom@kzsu.stanford.edu>'
abstract: extract elisp docstrings to html form
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Cwd: 0
  Date::Calc: 0
  Fatal: 0
  File::Copy: 0
  File::Path: 0
  FindBin: 0
  Test::Differences: 0
  Test::More: 0
  lib: 0
requires:
  Carp: 0
  Class::Base: 0
  Data::Dumper: 0
  Emacs::Run: 0
  Env: 0
  File::Basename: 0
  Hash::Util: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.35
provides:
  Emacs::Run::ExtractDocs:
    file: lib/Emacs/Run/ExtractDocs.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
