---
name: Emacs-Run-ExtractDocs
version: 0.02
author:
  - 'Joseph Brenner <doom@kzsu.stanford.edu>'
abstract: extract elisp docstrings to html form
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Emacs::Run::ExtractDocs:
    file: lib/Emacs/Run/ExtractDocs.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
